package org.apac.erp.cach.forecast.enumeration;

public enum DecaissementType {
	DECAISSEMENT_PLAN_COMPTABLE_TIERS, DECAISSEMENT_SALAIRE,
	DECAISSEMENT_INTERESTS,DECAISSEMENT_FACTURE_FOURNISSEUR, DECAISSEMENT_BANK_COMMISSION, DECAISSEMENT_AUTRE
}
