package org.apac.erp.cach.forecast.enumeration;

public enum EncaissementDecaissementType {
	ENCAISSEMENT_PLAN_COMPTABLE_TIERS, ENCAISSEMENT_AUTRE, DECAISSEMENT_PLAN_COMPTABLE_TIERS, DECAISSEMENT_SALAIRE,
	DECAISSEMENT_INTERESTS, DECAISSEMENT_BANK_COMMISSION, DECAISSEMENT_AUTRE

}
